# -*- coding: utf-8 -*-
"""RH_Práctica 07 _CLUSTERS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOD1a_OiMzZTmGuB8M9AnRGc0GVGXMVl

## **UNIVERSIDAD NACIONAL DE CHIMBORAZO**
## **FACULTAD DE INGENIERÍA**
## **CARRERA DE TECNOLOGÍAS DE LA INFORMACIÓN**

### **Asignatura:** Base de Datos Avanzadas
### **Práctica 07:** Clusters
### **Nombre:** Heidy Madeline Remache

## Librerías
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN

"""## Carga y lectura de datos"""

url = 'https://raw.githubusercontent.com/HeidyRemache/Database/main/casas.csv'
datos = np.loadtxt(url, delimiter = ",") #Ejecutar desde numpy

"""##Identificar Cluster"""

clusters = DBSCAN(eps = 2, min_samples = 10).fit_predict(datos)
clusters

plt.figure(figsize = (8,8))

plt.scatter(datos[:, 0], datos[:, 1], c = clusters, s = 100)
plt.xlabel("Años de construcción de la casa")
plt.ylabel("Precio")
plt.box(False)
plt.show()
