# -*- coding: utf-8 -*-
"""REGLAS DE ASOCIACION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9lKh5h_947dTfuLuL_t0O2j_OYm9Xx-
"""

!pip install efficient-apriori

from efficient_apriori import apriori

transacciones= [("leche", "pan", "huevo"),
                ("cereal","leche","crema","huevo"),
                ("leche","crema","pan","huevo"),
                ("crema","cereal"),
                ("huevo","cereal")]
conjuntos, reglas=apriori(transacciones,
                          min_support=0.3,
                          min_confidence=0.3)
reglas = filter(lambda regla: len(regla.rhs)==1,reglas)

for regla in reglas:
  print(regla)

